version: 0.2

phases:
  install: 
    runtime-versions:
      java: openjdk8
    commands:
      - sudo apt-get update
      - sudo apt-get install -y openjdk-8-jdk
      - sudo apt-get install -y maven
      - sudo apt-get install -y zip
  build:
    commands:
      - mvn clean install
artifacts:
  files:
    - target/webapp-1-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - beforeinstall.sh
    - applicationstart.sh
  discard-paths: yes
